version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - './conteneurs/database:/data'
    ports:
      - "6379:6379"

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - TEAM_NAME=Rubis